"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Award, CircleDollarSign, ClipboardList, FileText, GraduationCap, Plus, Trash2, Users } from "lucide-react";

type College = { id: number; name: string; category: string; interest: string; applicationType: string; deadline: string; major: string; status: string; netPrice: number; notes: string; essays: boolean; recommendations: boolean; transcript: boolean; fafsa: boolean };
type Accomplishment = { id: number; title: string; category: string; date: string; impact: string; evidence: string };
type Scholarship = { id: number; name: string; amount: number; deadline: string; status: string; url: string; requirements: string };
type AidOffer = { id: number; college: string; grants: number; scholarships: number; loans: number; workStudy: number; totalCost: number };
type Essay = { id: number; college: string; prompt: string; deadline: string; wordLimit: number; draft: string; status: string };
type Collaborator = { id: number; name: string; role: string; email: string };
type OrganizerData = { colleges: College[]; accomplishments: Accomplishment[]; scholarships: Scholarship[]; aidOffers: AidOffer[]; essays: Essay[]; collaborators: Collaborator[] };

const STORAGE_KEY = "clavisprep-organizer-v1";
const initialData: OrganizerData = { colleges: [], accomplishments: [], scholarships: [], aidOffers: [], essays: [], collaborators: [] };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export default function OrganizerPage() {
  const [data, setData] = useState<OrganizerData>(initialData);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState("overview");
  const [parentView, setParentView] = useState(false);
  const [collegeForm, setCollegeForm] = useState({ name: "", category: "match", interest: "High", applicationType: "Regular Decision", deadline: "", major: "", status: "Researching" });
  const [accomplishmentForm, setAccomplishmentForm] = useState({ title: "", category: "Activity", date: "", impact: "", evidence: "" });
  const [scholarshipForm, setScholarshipForm] = useState({ name: "", amount: "", deadline: "", status: "Considering", url: "", requirements: "" });
  const [aidForm, setAidForm] = useState({ college: "", grants: "", scholarships: "", loans: "", workStudy: "", totalCost: "" });
  const [essayForm, setEssayForm] = useState({ college: "", prompt: "", deadline: "", wordLimit: "650" });
  const [collaboratorForm, setCollaboratorForm] = useState({ name: "", role: "Parent", email: "" });

  useEffect(() => {
    // Hydrate the browser-only organizer draft after mount.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    try { setData(JSON.parse(localStorage.getItem(STORAGE_KEY) || JSON.stringify(initialData))); } catch { setData(initialData); }
    setReady(true);
  }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }, [data, ready]);

  const metrics = useMemo(() => {
    const collegeRequirements = data.colleges.flatMap(c => [c.essays, c.recommendations, c.transcript, c.fafsa]);
    const completedRequirements = collegeRequirements.filter(Boolean).length;
    const readiness = collegeRequirements.length ? Math.round((completedRequirements / collegeRequirements.length) * 100) : 0;
    const deadlines = [
      ...data.colleges.map(c => ({ title: `${c.name} application`, date: c.deadline, type: "Application" })),
      ...data.scholarships.map(s => ({ title: s.name, date: s.deadline, type: "Scholarship" })),
      ...data.essays.map(e => ({ title: `${e.college} essay`, date: e.deadline, type: "Essay" })),
    ].filter(item => item.date).sort((a, b) => a.date.localeCompare(b.date));
    const nextActions = [
      ...data.colleges.filter(c => !c.essays).map(c => `Finish essays for ${c.name}`),
      ...data.colleges.filter(c => !c.recommendations).map(c => `Request recommendations for ${c.name}`),
      ...data.scholarships.filter(s => s.status !== "Submitted" && s.status !== "Awarded").map(s => `Work on ${s.name}`),
      ...data.essays.filter(e => e.status !== "Final").map(e => `Continue ${e.college} essay`),
    ].slice(0, 3);
    return { readiness, deadlines, nextActions };
  }, [data]);

  const addCollege = (e: FormEvent) => { e.preventDefault(); setData(d => ({ ...d, colleges: [...d.colleges, { ...collegeForm, id: Date.now(), netPrice: 0, notes: "", essays: false, recommendations: false, transcript: false, fafsa: false }] })); setCollegeForm({ name: "", category: "match", interest: "High", applicationType: "Regular Decision", deadline: "", major: "", status: "Researching" }); };
  const addAccomplishment = (e: FormEvent) => { e.preventDefault(); setData(d => ({ ...d, accomplishments: [...d.accomplishments, { ...accomplishmentForm, id: Date.now() }] })); setAccomplishmentForm({ title: "", category: "Activity", date: "", impact: "", evidence: "" }); };
  const addScholarship = (e: FormEvent) => { e.preventDefault(); setData(d => ({ ...d, scholarships: [...d.scholarships, { ...scholarshipForm, amount: Number(scholarshipForm.amount) || 0, id: Date.now() }] })); setScholarshipForm({ name: "", amount: "", deadline: "", status: "Considering", url: "", requirements: "" }); };
  const addAid = (e: FormEvent) => { e.preventDefault(); setData(d => ({ ...d, aidOffers: [...d.aidOffers, { id: Date.now(), college: aidForm.college, grants: Number(aidForm.grants) || 0, scholarships: Number(aidForm.scholarships) || 0, loans: Number(aidForm.loans) || 0, workStudy: Number(aidForm.workStudy) || 0, totalCost: Number(aidForm.totalCost) || 0 }] })); setAidForm({ college: "", grants: "", scholarships: "", loans: "", workStudy: "", totalCost: "" }); };
  const addEssay = (e: FormEvent) => { e.preventDefault(); setData(d => ({ ...d, essays: [...d.essays, { id: Date.now(), college: essayForm.college, prompt: essayForm.prompt, deadline: essayForm.deadline, wordLimit: Number(essayForm.wordLimit) || 650, draft: "", status: "Not started" }] })); setEssayForm({ college: "", prompt: "", deadline: "", wordLimit: "650" }); };
  const addCollaborator = (e: FormEvent) => { e.preventDefault(); setData(d => ({ ...d, collaborators: [...d.collaborators, { ...collaboratorForm, id: Date.now() }] })); setCollaboratorForm({ name: "", role: "Parent", email: "" }); };
  const remove = (collection: keyof OrganizerData, id: number) => setData(d => ({ ...d, [collection]: d[collection].filter((item) => item.id !== id) }));
  const updateCollege = (id: number, patch: Partial<College>) => setData(d => ({ ...d, colleges: d.colleges.map(c => c.id === id ? { ...c, ...patch } : c) }));

  const tabs = [{ id: "overview", label: "Overview", icon: ClipboardList }, { id: "colleges", label: "Colleges", icon: GraduationCap }, { id: "accomplishments", label: "Portfolio", icon: Award }, { id: "scholarships", label: "Scholarships", icon: CircleDollarSign }, { id: "aid", label: "Aid Offers", icon: CircleDollarSign }, { id: "essays", label: "Essays", icon: FileText }, { id: "family", label: "Family", icon: Users }];
  return <main className="min-h-screen bg-slate-50">
    <header className="bg-blue-700 text-white"><div className="max-w-7xl mx-auto px-5 py-6"><Link href="/dashboard" className="inline-flex items-center gap-2 text-blue-100 text-sm"><ArrowLeft className="w-4 h-4" /> Dashboard</Link><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mt-4"><div><p className="text-blue-200 text-xs font-bold uppercase tracking-[.2em]">ClavisPrep</p><h1 className="text-3xl font-bold">College Organizer</h1><p className="text-blue-100 mt-1">Every college, deadline, document, dollar, essay, and accomplishment in one place.</p></div><button onClick={() => setParentView(!parentView)} className="bg-white text-blue-700 rounded-lg px-4 py-2 font-bold">{parentView ? "Student view" : "Parent view"}</button></div></div></header>
    <div className="max-w-7xl mx-auto px-5 py-6"><nav className="flex gap-2 overflow-x-auto pb-3">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`shrink-0 flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold ${tab === item.id ? "bg-blue-600 text-white" : "bg-white text-slate-600 border"}`}><Icon className="w-4 h-4" />{item.label}</button>; })}</nav>

    {tab === "overview" && <div className="space-y-6"><div className="grid md:grid-cols-4 gap-4"><Metric label="Readiness" value={`${metrics.readiness}%`} /><Metric label="Saved colleges" value={String(data.colleges.length)} /><Metric label="Scholarships" value={money.format(data.scholarships.reduce((s, x) => s + x.amount, 0))} /><Metric label="Accomplishments" value={String(data.accomplishments.length)} /></div><div className="grid lg:grid-cols-2 gap-6"><Card title="This week’s priorities"><ol className="space-y-3">{(metrics.nextActions.length ? metrics.nextActions : ["Add your first college", "Record a recent accomplishment", "Save a scholarship opportunity"]).map((action, i) => <li key={action} className="flex gap-3"><span className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-bold text-sm">{i + 1}</span><span>{action}</span></li>)}</ol></Card><Card title="Upcoming deadlines"><div className="space-y-3">{metrics.deadlines.slice(0, 6).map(item => <div key={`${item.type}-${item.title}`} className="flex justify-between gap-4 border-b pb-2"><div><p className="font-semibold">{item.title}</p><p className="text-xs text-slate-500">{item.type}</p></div><span className="text-sm text-blue-700 font-bold">{item.date}</span></div>)}{!metrics.deadlines.length && <Empty text="Add colleges, essays, or scholarships to create your calendar." />}</div></Card></div>{parentView && <FamilyReport data={data} readiness={metrics.readiness} />}</div>}

    {tab === "colleges" && <Section title="College workspaces" description="Track requirements and see exactly what remains for every application."><form onSubmit={addCollege} className="grid md:grid-cols-4 gap-3 bg-white p-4 rounded-xl border"><Input required label="College" value={collegeForm.name} onChange={e => setCollegeForm({ ...collegeForm, name: e.target.value })} /><Select label="Category" value={collegeForm.category} onChange={v => setCollegeForm({ ...collegeForm, category: v })} options={["reach", "match", "safety"]} /><Input label="Major" value={collegeForm.major} onChange={e => setCollegeForm({ ...collegeForm, major: e.target.value })} /><Input required type="date" label="Deadline" value={collegeForm.deadline} onChange={e => setCollegeForm({ ...collegeForm, deadline: e.target.value })} /><button className="md:col-span-4 bg-blue-600 text-white rounded-lg py-2 font-bold"><Plus className="inline w-4 h-4" /> Add college</button></form><div className="grid lg:grid-cols-2 gap-5 mt-5">{data.colleges.map(c => <Card key={c.id} title={c.name} action={<button onClick={() => remove("colleges", c.id)}><Trash2 className="w-4 h-4 text-red-500" /></button>}><div className="flex gap-2 text-xs mb-4"><Badge text={c.category} /><Badge text={c.applicationType} /></div>{(["essays", "recommendations", "transcript", "fafsa"] as const).map(field => <label key={field} className="flex items-center gap-2 py-2 border-b"><input type="checkbox" checked={c[field]} onChange={e => updateCollege(c.id, { [field]: e.target.checked })} /><span className="capitalize">{field}</span></label>)}<Select label="Application status" value={c.status} onChange={v => updateCollege(c.id, { status: v })} options={["Researching", "In progress", "Ready to submit", "Submitted", "Accepted", "Waitlisted", "Denied"]} /></Card>)}</div></Section>}

    {tab === "accomplishments" && <Section title="Accomplishment portfolio" description="Build the record that becomes the activities list, résumé, and application evidence."><form onSubmit={addAccomplishment} className="grid md:grid-cols-3 gap-3 bg-white p-4 rounded-xl border"><Input required label="Accomplishment" value={accomplishmentForm.title} onChange={e => setAccomplishmentForm({ ...accomplishmentForm, title: e.target.value })} /><Select label="Category" value={accomplishmentForm.category} onChange={v => setAccomplishmentForm({ ...accomplishmentForm, category: v })} options={["Activity", "Leadership", "Service", "Award", "Project", "Employment", "Certification"]} /><Input type="date" label="Date" value={accomplishmentForm.date} onChange={e => setAccomplishmentForm({ ...accomplishmentForm, date: e.target.value })} /><Input label="Impact or result" value={accomplishmentForm.impact} onChange={e => setAccomplishmentForm({ ...accomplishmentForm, impact: e.target.value })} /><Input label="Evidence or link" value={accomplishmentForm.evidence} onChange={e => setAccomplishmentForm({ ...accomplishmentForm, evidence: e.target.value })} /><button className="bg-blue-600 text-white rounded-lg font-bold">Add to portfolio</button></form><List items={data.accomplishments} remove={id => remove("accomplishments", id)} render={a => <><Badge text={a.category} /><h3 className="font-bold mt-2">{a.title}</h3><p className="text-sm text-slate-600">{a.impact}</p><p className="text-xs text-slate-500 mt-2">{a.date} {a.evidence && `• ${a.evidence}`}</p></>} /></Section>}

    {tab === "scholarships" && <Section title="Scholarship tracker" description="Match, verify, apply, and track awards—not merely a list of links."><form onSubmit={addScholarship} className="grid md:grid-cols-3 gap-3 bg-white p-4 rounded-xl border"><Input required label="Scholarship" value={scholarshipForm.name} onChange={e => setScholarshipForm({ ...scholarshipForm, name: e.target.value })} /><Input type="number" label="Amount" value={scholarshipForm.amount} onChange={e => setScholarshipForm({ ...scholarshipForm, amount: e.target.value })} /><Input type="date" label="Deadline" value={scholarshipForm.deadline} onChange={e => setScholarshipForm({ ...scholarshipForm, deadline: e.target.value })} /><Input label="Official link" value={scholarshipForm.url} onChange={e => setScholarshipForm({ ...scholarshipForm, url: e.target.value })} /><Input label="Requirements" value={scholarshipForm.requirements} onChange={e => setScholarshipForm({ ...scholarshipForm, requirements: e.target.value })} /><button className="bg-blue-600 text-white rounded-lg font-bold">Save scholarship</button></form><List items={data.scholarships} remove={id => remove("scholarships", id)} render={s => <><div className="flex justify-between"><Badge text={s.status} /><strong className="text-emerald-700">{money.format(s.amount)}</strong></div><h3 className="font-bold mt-2">{s.name}</h3><p className="text-sm text-slate-600">Due {s.deadline}</p>{s.url && <a className="text-blue-700 text-sm font-semibold" href={s.url} target="_blank">Official application →</a>}</>} /></Section>}

    {tab === "aid" && <Section title="Financial-aid offer comparison" description="Compare grants, scholarships, loans, work-study, and the actual remaining cost."><form onSubmit={addAid} className="grid md:grid-cols-3 gap-3 bg-white p-4 rounded-xl border"><Input required label="College" value={aidForm.college} onChange={e => setAidForm({ ...aidForm, college: e.target.value })} />{(["totalCost", "grants", "scholarships", "loans", "workStudy"] as const).map(field => <Input key={field} type="number" label={field.replace(/([A-Z])/g, " $1")} value={aidForm[field]} onChange={e => setAidForm({ ...aidForm, [field]: e.target.value })} />)}<button className="bg-blue-600 text-white rounded-lg font-bold">Add offer</button></form><div className="overflow-x-auto mt-5"><table className="w-full bg-white rounded-xl overflow-hidden"><thead className="bg-slate-100"><tr>{["College", "Cost", "Free aid", "Loans", "Work-study", "Remaining"].map(h => <th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody>{data.aidOffers.map(o => <tr key={o.id} className="border-t"><td className="p-3 font-bold">{o.college}</td><td className="p-3">{money.format(o.totalCost)}</td><td className="p-3 text-emerald-700">{money.format(o.grants + o.scholarships)}</td><td className="p-3">{money.format(o.loans)}</td><td className="p-3">{money.format(o.workStudy)}</td><td className="p-3 font-bold text-amber-700">{money.format(Math.max(0, o.totalCost - o.grants - o.scholarships - o.loans - o.workStudy))}</td></tr>)}</tbody></table></div></Section>}

    {tab === "essays" && <Section title="Essay workspace" description="Organize prompts, drafts, feedback, word limits, and deadlines by college."><form onSubmit={addEssay} className="grid md:grid-cols-4 gap-3 bg-white p-4 rounded-xl border"><Input required label="College" value={essayForm.college} onChange={e => setEssayForm({ ...essayForm, college: e.target.value })} /><Input required label="Prompt" value={essayForm.prompt} onChange={e => setEssayForm({ ...essayForm, prompt: e.target.value })} /><Input type="date" label="Deadline" value={essayForm.deadline} onChange={e => setEssayForm({ ...essayForm, deadline: e.target.value })} /><Input type="number" label="Word limit" value={essayForm.wordLimit} onChange={e => setEssayForm({ ...essayForm, wordLimit: e.target.value })} /><button className="md:col-span-4 bg-blue-600 text-white rounded-lg py-2 font-bold">Add essay</button></form><List items={data.essays} remove={id => remove("essays", id)} render={e => <><Badge text={e.status} /><h3 className="font-bold mt-2">{e.college}</h3><p className="text-sm text-slate-600 mt-1">{e.prompt}</p><p className="text-xs text-slate-500 mt-2">{e.wordLimit} words • Due {e.deadline}</p><Link href="/essay-coach" className="text-blue-700 text-sm font-semibold mt-3 inline-block">Open AI reviewer →</Link></>} /></Section>}

    {tab === "family" && <Section title="Family and counselor collaboration" description="Track who is helping. Sending invitations will be enabled when the organizer is deployed."><form onSubmit={addCollaborator} className="grid md:grid-cols-4 gap-3 bg-white p-4 rounded-xl border"><Input required label="Name" value={collaboratorForm.name} onChange={e => setCollaboratorForm({ ...collaboratorForm, name: e.target.value })} /><Select label="Role" value={collaboratorForm.role} onChange={v => setCollaboratorForm({ ...collaboratorForm, role: v })} options={["Parent", "Guardian", "Counselor", "Mentor", "Teacher"]} /><Input required type="email" label="Email" value={collaboratorForm.email} onChange={e => setCollaboratorForm({ ...collaboratorForm, email: e.target.value })} /><button className="bg-blue-600 text-white rounded-lg font-bold">Add collaborator</button></form><FamilyReport data={data} readiness={metrics.readiness} /><List items={data.collaborators} remove={id => remove("collaborators", id)} render={c => <><Badge text={c.role} /><h3 className="font-bold mt-2">{c.name}</h3><p className="text-sm text-slate-600">{c.email}</p></>} /></Section>}
    </div>
  </main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-white border rounded-xl p-5"><p className="text-sm text-slate-500">{label}</p><p className="text-3xl font-bold text-blue-700 mt-1">{value}</p></div>; }
function Input({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="text-sm font-medium text-slate-700">{label}<input {...props} className="mt-1 w-full border border-slate-300 rounded-lg px-3 py-2" /></label>; }
function Card({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="bg-white border rounded-xl p-5"><div className="flex justify-between"><h2 className="font-bold text-lg mb-4">{title}</h2>{action}</div>{children}</section>; }
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold">{title}</h2><p className="text-slate-600 mb-5">{description}</p>{children}</section>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-sm font-medium text-slate-700">{label}<select value={value} onChange={e => onChange(e.target.value)} className="mt-1 w-full border border-slate-300 rounded-lg px-3 py-2">{options.map(o => <option key={o}>{o}</option>)}</select></label>; }
function Badge({ text }: { text: string }) { return <span className="inline-flex px-2 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold capitalize">{text}</span>; }
function Empty({ text }: { text: string }) { return <p className="text-slate-500 text-sm py-5">{text}</p>; }
function List<T extends { id: number }>({ items, remove, render }: { items: T[]; remove: (id: number) => void; render: (item: T) => React.ReactNode }) { return <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-5">{items.map(item => <article key={item.id} className="bg-white border rounded-xl p-5 relative"><button onClick={() => remove(item.id)} className="absolute right-4 top-4"><Trash2 className="w-4 h-4 text-red-400" /></button>{render(item)}</article>)}</div>; }
function FamilyReport({ data, readiness }: { data: OrganizerData; readiness: number }) { const submitted = data.colleges.filter(c => ["Submitted", "Accepted"].includes(c.status)).length; return <Card title="Monthly family report"><div className="grid sm:grid-cols-3 gap-4"><div><p className="text-xs text-slate-500">Preparation</p><p className="font-bold text-2xl text-blue-700">{readiness}%</p></div><div><p className="text-xs text-slate-500">Applications submitted</p><p className="font-bold text-2xl">{submitted}/{data.colleges.length}</p></div><div><p className="text-xs text-slate-500">Portfolio items</p><p className="font-bold text-2xl">{data.accomplishments.length}</p></div></div><p className="text-sm text-slate-600 mt-4">This report turns activity, application, scholarship, essay, and financial progress into one parent-friendly monthly update.</p><button onClick={() => window.print()} className="mt-4 text-blue-700 font-bold text-sm">Print or save report →</button></Card>; }
